#!/usr/bin/env python3
"""Build and solve the order-10 band LP on the rebuilt 8-root envelope.

This is the certificate the repository set out to produce, on rows that are
actually valid.  Primal, over the 12,172 order-10 states:

    maximise  eta
    q >= 0,  sum q = 1,  LO <= <d_edge, q> <= HI,  <m, q> >= 0   (fixed Gram row)
    u_tau <= <h_{tau,c}, q>       for every rule c in the pool of root type tau
    eta   <= -2/25 + sum_tau u_tau

For a genuine triangle-free graphon W with state vector q(W) the point
`(q(W), u_tau = min over the pool, eta = sum u - 2/25)` is feasible, and
`d_mono(W) <= U8(W) <= sum_tau min_pool <= eta`, so a dual objective `delta`
proves `d_mono(W) <= 2/25 + delta` on the closed band.  `delta <= 0` is the
conjecture there.

Rows come from `rebuild_u8.py` (validated at the balanced C5 blow-up to machine
epsilon).  Summing over all isomorphisms root -> type is organised by orbits:
for each root type the ordered profile pairs are partitioned into Aut-orbits,
`N[o, s]` counts the raw incidences of orbit `o` in state `s`, and a rule `c`
contributes `f_c(o)` = fraction of pairs in `o` that `c` colours alike, so

    <h_{tau,c}, q>  =  (1/90) sum_o f_c(o) <N[o,:], q>.

Rules are generated by cutting planes: at each LP optimum `q*` the best rule
per root is a weighted MaxCut over the profile closure; a rule whose value
undercuts `u_tau*` becomes a new row.  The pool is seeded with the constant
rule (valid, weak) and with the MaxCut rules at a few genuine graphons.
"""

from __future__ import annotations

import argparse
import pickle
import random
import sys
import time
from pathlib import Path

import highspy
import numpy as np
from scipy.sparse import coo_matrix, csr_matrix

sys.path.insert(0, str(Path(__file__).resolve().parent))
from envelope_maxcut_bound import best_cut, exact_cut  # noqa: E402
from k7_leg_ceiling import (  # noqa: E402
    compositions, cycle, edges_of, grotzsch, multinomial, petersen,
)
from rebuild_u8 import Catalogue, automorphisms  # noqa: E402

N9, N10 = 1897, 12172
LO, HI = 2486 / 10000, 3197 / 10000
INF = highspy.kHighsInf


class RootData:
    """Orbit structure and incidence matrix of one root type."""

    def __init__(self, tau, adjacency, pair_counts):
        self.tau = tau
        group = automorphisms(adjacency)
        self.aut = len(group)
        profiles = sorted({p for key in pair_counts for p in key}, key=lambda p: (len(p), p))
        closure, index = list(profiles), {p: i for i, p in enumerate(profiles)}
        frontier = list(profiles)
        while frontier:
            nxt = []
            for g in group:
                for p in frontier:
                    moved = tuple(sorted(g[x] for x in p))
                    if moved not in index:
                        index[moved] = len(closure)
                        closure.append(moved)
                        nxt.append(moved)
            frontier = nxt
        self.closure = closure
        n = len(closure)
        self.width = n
        perm = np.asarray([[index[tuple(sorted(g[x] for x in p))] for p in closure]
                           for g in group], dtype=np.int64)
        orbit_of = -np.ones(n * n, dtype=np.int64)
        members = []
        rows, cols, vals = [], [], []
        for (a, b), bucket in pair_counts.items():
            pid = index[a] * n + index[b]
            if orbit_of[pid] < 0:
                orbit = np.unique(perm[:, index[a]] * n + perm[:, index[b]])
                orbit_of[orbit] = len(members)
                members.append(orbit)
            o = orbit_of[pid]
            for state, count in bucket.items():
                rows.append(o)
                cols.append(state)
                vals.append(count)
        self.members = members
        self.orbit_of = orbit_of
        self.sizes = np.asarray([len(m) for m in members], dtype=np.float64)
        self.N = coo_matrix((np.asarray(vals, dtype=np.float64), (rows, cols)),
                            shape=(len(members), N10)).tocsr()
        self.N.sum_duplicates()
        # rows of an orbit member pair, for fast colouring statistics
        self.member_a = [m // n for m in members]
        self.member_b = [m % n for m in members]

    def pair_weights(self, q):
        """closure x closure matrix of per-pair weights at q (sum = edge mass at tau)."""
        per_orbit = np.asarray(self.N @ q).ravel() / (90.0 * self.sizes)
        W = np.zeros((self.width, self.width))
        for o, m in enumerate(self.members):
            if per_orbit[o]:
                W.flat[m] = per_orbit[o]
        return W

    def rule_row(self, colouring):
        """Coefficient vector over states: <h_{tau,c}, q> = row . q ."""
        c = np.asarray(colouring, dtype=np.int8)
        f = np.asarray([float(np.mean(c[a] == c[b])) for a, b in
                        zip(self.member_a, self.member_b)])
        return np.asarray(f @ self.N).ravel() / 90.0

    def form_row(self, coefficients):
        """Aut-averaged row of an arbitrary closure x closure coefficient matrix."""
        flat = np.asarray(coefficients, dtype=float).ravel()
        f = np.asarray([float(flat[m].mean()) for m in self.members])
        return np.asarray(f @ self.N).ravel() / 90.0

    def horn_search(self, q, rng, restarts=30):
        """Most violated rooted-Horn 5-cycle at q: (value, cycle) with value < 0 if found."""
        M = self.pair_weights(q)
        M = (M + M.T) / 2.0
        n = self.width
        support = np.nonzero(M.sum(axis=1))[0]
        if len(support) < 5:
            return 0.0, None

        def value(cyc):
            idx = list(cyc)
            block = M[np.ix_(idx, idx)].sum()
            ring = sum(M[idx[i], idx[(i + 1) % 5]] for i in range(5))
            return block - 4.0 * ring

        found = {}
        for _ in range(restarts):
            cyc = list(rng.sample(list(support), 5))
            cur = value(cyc)
            improved = True
            while improved:
                improved = False
                for pos in range(5):
                    for cand in support:
                        if cand in cyc:
                            continue
                        trial = cyc.copy()
                        trial[pos] = int(cand)
                        v = value(trial)
                        if v < cur - 1e-15:
                            cyc, cur, improved = trial, v, True
            if cur < -1e-9:
                variants = [tuple(cyc[i:] + cyc[:i]) for i in range(5)]
                rev = cyc[::-1]
                variants += [tuple(rev[i:] + rev[:i]) for i in range(5)]
                found[min(variants)] = (cur, cyc)
        cycles = sorted(found.values(), key=lambda t: t[0])
        self.last_cycles = cycles
        if not cycles:
            return 0.0, None
        return cycles[0]

    def horn_coefficients(self, cyc):
        C = np.zeros((self.width, self.width))
        C[np.ix_(cyc, cyc)] = 1.0
        for i in range(5):
            C[cyc[i], cyc[(i + 1) % 5]] -= 4.0
        return C

    def best_rule(self, q, rng, starts):
        """Best rule at q by MaxCut; returns (colouring, value)."""
        W = self.pair_weights(q)
        W = (W + W.T) / 2.0
        diag = float(np.trace(W))
        upper = np.triu(W, 1)
        S = float(upper.sum())
        sym = upper + upper.T
        active = np.nonzero(sym.sum(axis=1) + np.diag(W))[0]
        colouring = np.zeros(self.width, dtype=np.int8)
        if len(active) > 1:
            sub = sym[np.ix_(active, active)]
            if len(active) <= 18:
                cut, x = exact_cut_with_arg(sub)
            else:
                cut, x = best_cut_with_arg(sub, starts, rng)
            colouring[active] = x
        else:
            cut = 0.0
        return colouring, diag + 2.0 * (S - cut)


class MomentBlocks:
    """Eigenvector cuts from the order-9 flag moment matrices, lifted to order 10.

    For a type with matrices `mats[s]` (k x k, integer) and normalisers `den[s]`,
    the moment matrix at an order-9 distribution `q9` is
    `M(q9) = sum_s q9[s] mats[s] / den[s]`, positive semidefinite at every
    graphon.  With `q9 = D q10` (the deletion lift), the row `v^T M(q10) v >= 0`
    is linear in `q10` with coefficients `D^T w`, `w[s] = v^T mats[s] v / den[s]`.
    The shipped fixed-Gram row is a nonnegative combination of 87 such rows.
    """

    def __init__(self, cache, lift):
        from math import comb, prod
        self.D = csr_matrix((np.asarray(lift["Dval"], dtype=float),
                             (lift["Drow"], lift["Dcol"])), shape=(N9, N10))
        self.Dt = self.D.T.tocsr()
        self.blocks = []
        states = cache["states"]
        for label, _size, sigma, _flags, free_size, _flat, mats in cache["moments"]:
            root_size = sigma[0]
            den = np.asarray([
                prod(order - i for i in range(root_size)) * comb(order - root_size, free_size) ** 2
                if order - root_size >= free_size else 1
                for order, _adj in states], dtype=float)
            self.blocks.append((label, np.asarray(mats, dtype=float) / den[:, None, None]))

    def matrices(self, q10):
        q9 = np.asarray(self.D @ q10).ravel()
        return [(label, np.einsum("s,sij->ij", q9, scaled)) for label, scaled in self.blocks]

    def cut_row(self, block_index, v):
        _label, scaled = self.blocks[block_index]
        w = np.einsum("i,sij,j->s", v, scaled, v)
        return np.asarray(self.Dt @ w).ravel()

    def separate(self, q10, tol=1e-9, per_block=3):
        cuts = []
        for b, (label, M) in enumerate(self.matrices(q10)):
            vals, vecs = np.linalg.eigh((M + M.T) / 2.0)
            for j in range(min(per_block, len(vals))):
                if vals[j] < -tol:
                    cuts.append((label, float(vals[j]), self.cut_row(b, vecs[:, j]),
                                 (b, vecs[:, j].copy())))
        return cuts


def exact_cut_with_arg(weights):
    n = weights.shape[0]
    iu, ju = np.triu_indices(n, 1)
    w = weights[iu, ju]
    keep = w != 0
    iu, ju, w = iu[keep], ju[keep], w[keep]
    patterns = np.arange(1 << (n - 1), dtype=np.int64)
    bits = ((patterns[:, None] >> np.arange(n - 1)[None, :]) & 1).astype(np.int8)
    full = np.concatenate([np.zeros((len(patterns), 1), dtype=np.int8), bits], axis=1)
    cuts = ((full[:, iu] != full[:, ju]) * w[None, :]).sum(axis=1)
    k = int(np.argmax(cuts))
    return float(cuts[k]), full[k]


def best_cut_with_arg(weights, starts, rng):
    n = weights.shape[0]
    best, best_x = -1.0, None
    for attempt in range(starts):
        x = (np.zeros(n, dtype=np.int8) if attempt == 0
             else np.asarray([rng.random() < 0.5 for _ in range(n)], dtype=np.int8))
        while True:
            diff = x[:, None] != x[None, :]
            gain = (weights * ~diff).sum(axis=1) - (weights * diff).sum(axis=1)
            i = int(np.argmax(gain))
            if gain[i] <= 1e-12:
                break
            x[i] ^= 1
        value = float((np.triu(weights, 1) * (x[:, None] != x[None, :])).sum())
        if value > best:
            best, best_x = value, x.copy()
    return best, best_x


def q10_of(cat9, profile_to_state, base, weights):
    h = len(base)
    index9 = {}
    for parts in compositions(9, h):
        blocks, idx = [], 0
        for size in parts:
            blocks.append(list(range(idx, idx + size)))
            idx += size
        adjacency = [0] * idx
        for x in range(h):
            for y in range(x + 1, h):
                if (base[x] >> y) & 1:
                    for p in blocks[x]:
                        for r in blocks[y]:
                            adjacency[p] |= 1 << r
                            adjacency[r] |= 1 << p
        index9[parts] = cat9.find(adjacency)[0]
    q = np.zeros(N10)
    for parts in compositions(10, h):
        profile = {}
        for i in range(h):
            if parts[i]:
                reduced = list(parts)
                reduced[i] -= 1
                j = index9[tuple(reduced)]
                profile[j] = profile.get(j, 0) + parts[i]
        state = profile_to_state[tuple(sorted(profile.items()))]
        q[state] += multinomial(parts) * float(np.prod(np.power(weights, parts)))
    return q / q.sum()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--flagsdp", type=Path, required=True)
    parser.add_argument("--public-anc", type=Path, required=True)
    parser.add_argument("--rebuilt", type=Path, required=True)
    parser.add_argument("--iterations", type=int, default=40)
    parser.add_argument("--starts", type=int, default=8)
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument("--allpairs", type=Path, default=None,
                        help="all-pairs decomposition from rebuild_u8_allpairs.py; enables Horn rows")
    parser.add_argument("--horn-restarts", type=int, default=20)
    parser.add_argument("--psd", action="store_true",
                        help="add eigenvector cuts from the order-9 moment matrices")
    parser.add_argument("--horn-per-root", type=int, default=3)
    parser.add_argument("--time-limit", type=float, default=2400.0)
    parser.add_argument("--max-rules", type=int, default=150, help="rule rows added per iteration")
    parser.add_argument("--max-horn", type=int, default=150, help="Horn rows added per iteration")
    parser.add_argument("--drop-after", type=int, default=3,
                        help="drop a non-static row after this many consecutive slack solves")
    parser.add_argument("--root-psd", action="store_true",
                        help="eigenvector cuts from the 8-root pair matrices themselves "
                             "(the s=8 blocks of the order-10 flag SDP)")
    parser.add_argument("--rpsd-per-root", type=int, default=2)
    parser.add_argument("--max-rpsd", type=int, default=150)
    parser.add_argument("--blocks10", default=None,
                        help="type sizes of the order-10 flag moment blocks to cut on, e.g. 024 or 0246")
    parser.add_argument("--b10-per-block", type=int, default=3)
    parser.add_argument("--max-b10", type=int, default=150)
    parser.add_argument("--work", type=Path, default=Path(".work"))
    parser.add_argument("--solver", default="simplex", choices=["simplex", "ipm", "pdlp"])
    parser.add_argument("--in-out", type=float, default=0.0,
                        help="in-out separation: separate PSD/Horn cuts at lambda*q_out + (1-lambda)*q_in, "
                             "q_in a mixture of graphon state vectors (0 = off)")
    parser.add_argument("--in-out-bases", type=int, default=40)
    parser.add_argument("--crossover", default="on", choices=["on", "off"])
    parser.add_argument("--slack-tol", type=float, default=None,
                        help="a row whose |dual| stays below this counts as slack (default 1e-12, 1e-7 for ipm)")
    parser.add_argument("--checkpoint", type=Path, default=None)
    parser.add_argument("--resume", type=Path, default=None)
    args = parser.parse_args()
    started = time.time()

    with args.rebuilt.open("rb") as handle:
        payload = pickle.load(handle)
    states10, roots8, pairs = payload["states10"], payload["roots8"], payload["pairs"]
    with (args.flagsdp / "cache_n9.pkl").open("rb") as handle:
        cache9 = pickle.load(handle)
    states9 = [list(masks) for _o, masks in cache9["states"]]
    cat9 = Catalogue(states9)
    lift = np.load(args.flagsdp / "c5lift_cache.npz", allow_pickle=True)
    moments = MomentBlocks(cache9, lift) if args.psd else None
    blocks10 = None
    if args.blocks10:
        from blocks10 import Blocks10
        blocks10 = Blocks10(states10, args.work, args.blocks10)
        print(f"order-10 blocks: {len(blocks10.keys)} types, widths up to {max(blocks10.sizes)}"
              f"  [{time.time() - started:.0f}s]", flush=True)
    counts = np.rint(np.asarray(lift["Dval"]) * 10).astype(np.int64)
    columns = csr_matrix((counts, (lift["Drow"], lift["Dcol"])),
                         shape=(N9, N10), dtype=np.int64).tocsc()
    profile_to_state = {}
    for j in range(N10):
        s, e = columns.indptr[j], columns.indptr[j + 1]
        profile_to_state[tuple(sorted(zip(columns.indices[s:e].tolist(),
                                          columns.data[s:e].tolist())))] = j

    d_edge = np.asarray([sum(bin(m).count("1") for m in adj) / 2 / 45.0 for adj in states10])
    with (args.public_anc / "mom_term_exact.pkl").open("rb") as handle:
        moment = np.asarray([n / d for n, d in pickle.load(handle)], dtype=float)

    roots = []
    for tau in range(410):
        roots.append(RootData(tau, roots8[tau], pairs[tau]) if pairs[tau] else None)
    live = [r for r in roots if r is not None]
    horn_roots = []
    if args.allpairs:
        with args.allpairs.open("rb") as handle:
            all_pairs = pickle.load(handle)["pairs"]
        horn_roots = [RootData(tau, roots8[tau], all_pairs[tau]) for tau in range(410)
                      if all_pairs[tau]]
        total = sum(r.form_row(np.ones((r.width, r.width))) for r in horn_roots)
        print(f"all-pairs data: {len(horn_roots)} types; all-ones check "
              f"max |sum - 1| = {np.abs(total - 1.0).max():.3e}  [{time.time() - started:.0f}s]",
              flush=True)
    print(f"root data: {len(live)} live types, closure widths up to "
          f"{max(r.width for r in live)}, orbits up to {max(len(r.members) for r in live)}"
          f"  [{time.time() - started:.0f}s]", flush=True)

    # sanity: the constant rule reproduces d_edge exactly
    ones = sum(r.rule_row(np.zeros(r.width, dtype=np.int8)) for r in live)
    print(f"constant-rule check: max |sum_tau h_const - d_edge| = "
          f"{np.abs(ones - d_edge).max():.3e}")

    rng = random.Random(2026)

    # ---- LP ----------------------------------------------------------------
    col_eta = N10
    col_u = {r.tau: N10 + 1 + i for i, r in enumerate(live)}
    ncols = N10 + 1 + len(live)
    h = highspy.Highs()
    h.setOptionValue("output_flag", False)
    h.setOptionValue("presolve", "on")
    h.setOptionValue("solver", args.solver)
    h.setOptionValue("run_crossover", args.crossover)
    lower = np.zeros(ncols)
    upper = np.full(ncols, INF)
    lower[col_eta] = -INF
    h.addVars(ncols, lower, upper)
    cost = np.zeros(ncols)
    cost[col_eta] = -1.0                      # HiGHS minimises; we maximise eta
    h.changeColsCost(ncols, np.arange(ncols, dtype=np.int32), cost)

    def add_row(indices, values, lo, hi):
        h.addRow(lo, hi, len(indices), np.asarray(indices, dtype=np.int32),
                 np.asarray(values, dtype=float))

    qcols = np.arange(N10)
    add_row(qcols, d_edge, LO, HI)                               # band (two-sided)
    add_row(qcols, moment, 0.0, INF)                              # fixed Gram row
    add_row(qcols, np.ones(N10), 1.0, 1.0)                       # mass
    add_row([col_eta] + [col_u[r.tau] for r in live],
            [1.0] + [-1.0] * len(live), -INF, -2.0 / 25.0)       # eta <= -2/25 + sum u
    static_rows = 4

    pool = {r.tau: [] for r in live}
    rows_log = [("band", None, None), ("gram", None, None), ("mass", None, None), ("leg8", None, None)]
    slack = [0, 0, 0, 0]
    root_by_tau = {r.tau: r for r in live}
    horn_by_tau = {r.tau: r for r in horn_roots}

    def checkpoint(eta, x, duals):
        if args.checkpoint:
            with args.checkpoint.open("wb") as handle:
                pickle.dump({"eta": eta, "q": x[:N10],
                             "u": {r.tau: float(x[col_u[r.tau]]) for r in live},
                             "duals": duals, "rows": rows_log, "col_u": col_u}, handle)

    def add_rule(r, colouring):
        row = r.rule_row(colouring)
        nz = np.nonzero(row)[0]
        add_row(np.concatenate([nz, [col_u[r.tau]]]),
                np.concatenate([-row[nz], [1.0]]), -INF, 0.0)
        pool[r.tau].append(np.asarray(colouring, dtype=np.int8))
        rows_log.append(("rule", r.tau, np.asarray(colouring, dtype=np.int8)))
        slack.append(0)

    seeds = [("C5", cycle(5), np.full(5, 0.2)),
             ("Grotzsch", grotzsch(), np.asarray(
                 [10173, 9717, 8691, 10166, 7628, 8213, 7344, 9352, 12084, 10443, 6189], float)),
             ("Petersen", petersen(), np.full(10, 0.1))]
    seed_vectors = []
    for name, base, w in seeds:
        seed_vectors.append((name, q10_of(cat9, profile_to_state, base, w / w.sum())))
    q_in = None
    lam = args.in_out
    if args.in_out > 0:
        # a mixture of many weighted blow-ups of small triangle-free graphs: every valid
        # inequality holds at it, and its moment matrices are well inside the cone
        mix = [q for _n, q in seed_vectors]
        np_rng = np.random.default_rng(7)
        # order-7 triangle-free graphs: the order-9 states restricted to their first 7 vertices
        bases, seen = [], set()
        for _o, masks in cache9["states"]:
            adj = [m & 0x7F for m in list(masks)[:7]]
            key = tuple(adj)
            if key in seen or sum(bin(m).count("1") for m in adj) < 6:
                continue
            seen.add(key)
            bases.append(adj)
        np_rng.shuffle(bases)
        for adj in bases[:args.in_out_bases]:
            w = np_rng.dirichlet(np.ones(7))
            mix.append(q10_of(cat9, profile_to_state, adj, w))
        q_in = np.mean(mix, axis=0)
        print(f"in-out: q_in from {len(mix)} graphon state vectors, support {int((q_in > 0).sum())}, "
              f"d_edge {d_edge @ q_in:.4f}, lambda {lam}  [{time.time() - started:.0f}s]", flush=True)
    if args.resume and args.resume.exists():
        with args.resume.open("rb") as handle:
            saved = pickle.load(handle)
        restored = 0
        pending_b10 = []
        for kind, a, b in saved["rows"]:
            if kind == "rule":
                add_rule(root_by_tau[a], np.asarray(b, dtype=np.int8))
            elif kind == "horn":
                row = horn_by_tau[a].form_row(horn_by_tau[a].horn_coefficients(list(b)))
                nz = np.nonzero(row)[0]
                add_row(nz, row[nz], 0.0, INF)
                rows_log.append(("horn", a, list(b)))
                slack.append(0)
            elif kind == "psd":
                block_index, vec = b
                row = moments.cut_row(block_index, np.asarray(vec))
                nz = np.nonzero(row)[0]
                add_row(nz, row[nz], 0.0, INF)
                rows_log.append(("psd", a, (block_index, np.asarray(vec))))
                slack.append(0)
            elif kind == "rpsd":
                vec = np.asarray(b, dtype=float)
                row = horn_by_tau[a].form_row(np.outer(vec, vec))
                nz = np.nonzero(row)[0]
                add_row(nz, row[nz], 0.0, INF)
                rows_log.append(("rpsd", a, vec))
                slack.append(0)
            elif kind == "b10":
                pending_b10.append((tuple(a), np.asarray(b, dtype=np.int64)))
                continue
            else:
                continue
            restored += 1
        if pending_b10:
            if blocks10 is None:
                raise RuntimeError("the checkpoint has order-10 block rows; pass --blocks10")
            for (key, vec), row in zip(pending_b10, blocks10.float_rows(pending_b10)):
                nz = np.nonzero(row)[0]
                add_row(nz, row[nz], 0.0, INF)
                rows_log.append(("b10", key, vec))
                slack.append(0)
                restored += 1
        print(f"resumed {restored} rows from {args.resume} (eta was {saved['eta']:+.6e})"
              f"  [{time.time() - started:.0f}s]", flush=True)
    else:
        for r in live:
            add_rule(r, np.zeros(r.width, dtype=np.int8))
        for name, q in seed_vectors:
            added = 0
            for r in live:
                colouring, _ = r.best_rule(q, rng, args.starts)
                add_rule(r, colouring)
                added += 1
            print(f"seeded {added} rules from {name}  [{time.time() - started:.0f}s]", flush=True)

    # ---- cutting planes ------------------------------------------------------
    history = []
    for it in range(args.iterations):
        h.run()
        status = h.modelStatusToString(h.getModelStatus())
        sol = h.getSolution()
        x = np.asarray(sol.col_value)
        q, eta = x[:N10], float(x[col_eta])
        duals_now = np.asarray(sol.row_dual)
        checkpoint(eta, x, duals_now)
        # drop rows that have been slack for several consecutive solves
        slack_tol = args.slack_tol if args.slack_tol is not None else (1e-7 if args.solver == "ipm" else 1e-12)
        for i in range(len(rows_log)):
            if abs(duals_now[i]) < slack_tol:
                slack[i] += 1
            else:
                slack[i] = 0
        droppable = [i for i in range(4, len(rows_log))
                     if slack[i] >= args.drop_after
                     and not (rows_log[i][0] == "rule" and not np.any(rows_log[i][2]))]
        if droppable:
            h.deleteRows(len(droppable), np.asarray(droppable, dtype=np.int32))
            keep = [i for i in range(len(rows_log)) if i not in set(droppable)]
            rows_log[:] = [rows_log[i] for i in keep]
            slack[:] = [slack[i] for i in keep]
            for tau in pool:
                pool[tau] = [c for (k, t, c) in rows_log if k == "rule" and t == tau]
        q_sep = q if q_in is None else lam * q + (1.0 - lam) * q_in
        found_cuts = kept_cuts = 0
        candidates = []
        for r in live:
            u_star = float(x[col_u[r.tau]])
            colouring, value = r.best_rule(q, rng, args.starts)
            if value < u_star - 1e-9:
                candidates.append((u_star - value, r, colouring))
        candidates.sort(key=lambda t: -t[0])
        added = 0
        worst = candidates[0][0] if candidates else 0.0
        for viol, r, colouring in candidates[:args.max_rules]:
            add_rule(r, colouring)
            added += 1
        horns = 0
        horn_worst = 0.0
        horn_candidates = []
        for r in horn_roots:
            val, cyc = r.horn_search(q_sep, rng, args.horn_restarts)
            if cyc is None:
                continue
            for val, cyc in r.last_cycles[:args.horn_per_root]:
                horn_candidates.append((val, r, cyc))
        horn_candidates.sort(key=lambda t: t[0])
        for val, r, cyc in horn_candidates[:args.max_horn]:
            row = r.form_row(r.horn_coefficients(cyc))
            found_cuts += 1
            if q_in is not None and float(row @ q) > -1e-12:
                continue
            kept_cuts += 1
            for name, qs in seed_vectors:            # validity gate
                check = float(row @ qs)
                if check < -1e-12:
                    raise RuntimeError(f"INVALID Horn row at root {r.tau}: "
                                       f"value {check:+.3e} at {name}")
            nz = np.nonzero(row)[0]
            add_row(nz, row[nz], 0.0, INF)
            rows_log.append(("horn", r.tau, list(cyc)))
            slack.append(0)
            horns += 1
            horn_worst = min(horn_worst, val)
        psd_cuts = 0
        psd_worst = 0.0
        if moments is not None:
            for label, lam_psd, row, vec in moments.separate(q_sep):
                for name, qs in seed_vectors:            # validity gate
                    check = float(row @ qs)
                    if check < -1e-9:
                        raise RuntimeError(f"INVALID PSD cut ({label}): {check:+.3e} at {name}")
                found_cuts += 1
                if q_in is not None and float(row @ q) > -1e-12:
                    continue
                kept_cuts += 1
                nz = np.nonzero(row)[0]
                add_row(nz, row[nz], 0.0, INF)
                rows_log.append(("psd", label, vec))
                slack.append(0)
                psd_cuts += 1
                psd_worst = min(psd_worst, lam_psd)
        rpsd_cuts = 0
        rpsd_worst = 0.0
        if args.root_psd:
            rpsd_candidates = []
            for r in horn_roots:
                M = r.pair_weights(q_sep)
                M = (M + M.T) / 2.0
                if not M.any():
                    continue
                vals, vecs = np.linalg.eigh(M)
                for j in range(min(args.rpsd_per_root, len(vals))):
                    if vals[j] < -1e-9:
                        rpsd_candidates.append((float(vals[j]), r, vecs[:, j].copy()))
            rpsd_candidates.sort(key=lambda t: t[0])
            for lam_r, r, vec in rpsd_candidates[:args.max_rpsd]:
                row = r.form_row(np.outer(vec, vec))
                for name, qs in seed_vectors:            # validity gate
                    check = float(row @ qs)
                    if check < -1e-9:
                        raise RuntimeError(f"INVALID root-PSD cut at root {r.tau}: "
                                           f"{check:+.3e} at {name}")
                found_cuts += 1
                if q_in is not None and float(row @ q) > -1e-12:
                    continue
                kept_cuts += 1
                nz = np.nonzero(row)[0]
                add_row(nz, row[nz], 0.0, INF)
                rows_log.append(("rpsd", r.tau, vec))
                slack.append(0)
                rpsd_cuts += 1
                rpsd_worst = min(rpsd_worst, lam_r)
        b10_cuts = 0
        b10_worst = 0.0
        if blocks10 is not None:
            found = sorted(blocks10.separate(q_sep, per_block=args.b10_per_block), key=lambda c: c[1])
            for key, lam_b, row, vec in found[:args.max_b10]:
                for name, qs in seed_vectors:            # validity gate
                    check = float(row @ qs)
                    if check < -1e-9:
                        raise RuntimeError(f"INVALID order-10 block cut {key}: {check:+.3e} at {name}")
                found_cuts += 1
                if q_in is not None and float(row @ q) > -1e-12:
                    continue
                kept_cuts += 1
                nz = np.nonzero(row)[0]
                add_row(nz, row[nz], 0.0, INF)
                rows_log.append(("b10", key, vec))
                slack.append(0)
                b10_cuts += 1
                b10_worst = min(b10_worst, lam_b)
        if q_in is not None:
            # adapt: when few cuts found at the inner point still cut the optimum, move outward
            if found_cuts and kept_cuts < 0.5 * found_cuts:
                lam = min(1.0, lam + 0.1)
            elif found_cuts == 0:
                lam = min(1.0, lam + 0.2)
        history.append((it, eta, added, horns, psd_cuts, rpsd_cuts, b10_cuts))
        print(f"iter {it:3d}: status={status} eta={eta:+.6e} band={d_edge @ q:.4f} "
              f"rules +{added} (viol {worst:.1e}) horn +{horns} ({horn_worst:+.1e}) "
              f"psd +{psd_cuts} ({psd_worst:+.1e}) rpsd +{rpsd_cuts} ({rpsd_worst:+.1e}) "
              f"b10 +{b10_cuts} ({b10_worst:+.1e}) "
              f"dropped {len(droppable)} rows={len(rows_log)}"
              + (f" in-out {kept_cuts}/{found_cuts} lam={lam:.2f}" if q_in is not None else "")
              + f"  [{time.time() - started:.0f}s]", flush=True)
        if added == 0 and horns == 0 and psd_cuts == 0 and rpsd_cuts == 0 and b10_cuts == 0:
            print("no violated rows found: converged for these families", flush=True)
            break
        if eta <= 0:
            print("eta <= 0 reached", flush=True)
            break
        if time.time() - started > args.time_limit:
            print("time limit reached", flush=True)
            break

    # ---- report --------------------------------------------------------------
    h.run()
    sol = h.getSolution()
    x = np.asarray(sol.col_value)
    duals = np.asarray(sol.row_dual)
    eta = float(x[col_eta])
    print("\n=== result ===")
    print(f"LP optimum eta = {eta:+.9e}   (delta of the certificate)")
    print(f"band activity  = {d_edge @ x[:N10]:.6f}   dual on band row = {duals[0]:+.6e}")
    print(f"moment row dual = {duals[1]:+.6e}   mass dual (rho) = {duals[2]:+.6e}")
    print(f"pool size = {sum(map(len, pool.values()))} rules over {len(live)} roots")
    if eta <= 0:
        print("VERDICT: eta <= 0 -- the rebuilt 8-root LP certifies d_mono <= 2/25 + eta on the band.")
    else:
        print("VERDICT: eta > 0 -- this relaxation (band + mass + one Gram row) is not enough;"
              " Horn rows / more PSD rows are needed.")
    if args.out:
        with args.out.open("wb") as handle:
            pickle.dump({"eta": eta, "q": x[:N10], "u": {r.tau: float(x[col_u[r.tau]]) for r in live},
                         "duals": duals, "pool": pool, "history": history,
                         "rows": rows_log, "col_u": col_u}, handle)
    print(f"total {time.time() - started:.0f}s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
